project_id = "cwelwumbofszrdenbkmw"

[functions.calculate-points]
verify_jwt = false

[functions.predict-match]
verify_jwt = false

[functions.calculate-topscorer-points]
verify_jwt = false

[functions.calculate-winner-points]
verify_jwt = false

[functions.calculate-group-points]
verify_jwt = false

[functions.send-deadline-notifications]
verify_jwt = false
